import type { NextPage } from 'next'
import Head from 'next/head'
import Nav from 'components/Nav'

const Home: NextPage = () => {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen">
      <Head>
        <title>Create Next Cosmos Keplr App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
        <h1 className="text-6xl font-bold">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className="mt-3 text-2xl">
          Get started by installing{' '}
          <a className="pl-1 text-blue-600" href="https://keplr.app/">
            Keplr wallet
          </a>
        </p>

        <div className="flex flex-wrap items-center justify-around max-w-4xl mt-6 sm:w-full">
          <a
            href="#"
            className="p-6 mt-6 text-left border w-96 rounded-xl hover:text-blue-600 focus:text-blue-600"
          >
            <h3 className="text-2xl font-bold">Connect your wallet &rarr;</h3>
            <p className="mt-4 text-xl">
              Get your Keplr wallet connected now and start using it with
              Cosmos.js.
            </p>
          </a>
        </div>
      </main>

      <footer className="flex items-center justify-center w-full h-24 border-t">
        Powered by{' '}
        <a
          className="pl-1 text-blue-600"
          href="https://github.com/cosmostation/cosmosjs"
        >
          CosmosJS
        </a>
        <span className="pl-1"> and</span>
        <a className="pl-1 text-blue-600" href="https://keplr.app/">
          Keplr
        </a>
      </footer>
    </div>
  )
}

export default Home
